import type {
    ExerciseDefinitionAvailability,
    ExerciseDefinitionSource,
} from '@src/core/entities/exerciseDefinition.interfaces';

import { normalizeExerciseName } from './normalizeExerciseName';

const SYSTEM_EXERCISE_CREATED_AT_MS = 1_700_000_000_000;

export interface SystemExerciseDefinitionSeed {
    availability: ExerciseDefinitionAvailability;
    createdAtMs: number;
    name: string;
    normalizedName: string;
    source: ExerciseDefinitionSource;
    updatedAtMs: number;
}

const systemExerciseDefinitionSeeds = [
    'Air Bike',
    'Air Squat',
    'Arnold Press',
    'Back Extension',
    'Back Squat',
    'Battle Rope Slam',
    'Bear Crawl',
    'Bench Dip',
    'Bench Press',
    'Bent Over Row',
    'Bicep Curl',
    'Bicycle Crunch',
    'Bird Dog',
    'Box Jump',
    'Broad Jump',
    'Bulgarian Split Squat',
    'Burpee',
    'Burpee Box Jump',
    'Burpee Broad Jump',
    'Burpee Push Up',
    'Cable Crossover',
    'Calf Raise',
    'Chest Fly',
    'Chest Press',
    'Chin Up',
    'Clean',
    'Clean and Jerk',
    'Clean and Press',
    'Close Grip Bench Press',
    'Close Grip Push Up',
    'Concentration Curl',
    'Crunch',
    'Curtsy Lunge',
    'Dead Bug',
    'Deadlift',
    'Decline Bench Press',
    'Decline Push Up',
    'Diamond Push Up',
    'Dip',
    'Donkey Kick',
    'Double Unders',
    'Dumbbell Bench Press',
    'Dumbbell Curl',
    'Dumbbell Fly',
    'Dumbbell Front Raise',
    'Dumbbell Lateral Raise',
    'Dumbbell Press',
    'Dumbbell Row',
    'Dumbbell Shoulder Press',
    'Dumbbell Snatch',
    'Face Pull',
    'Farmer Carry',
    'Fire Hydrant',
    'Flutter Kick',
    'Forward Lunge',
    'Front Raise',
    'Front Squat',
    'Glute Bridge',
    'Goblet Squat',
    'Good Morning',
    'Hack Squat',
    'Hammer Curl',
    'Handstand Hold',
    'Handstand Push Up',
    'Hanging Knee Raise',
    'Hanging Leg Raise',
    'High Knees',
    'Hip Thrust',
    'Hollow Hold',
    'Incline Bench Press',
    'Incline Dumbbell Press',
    'Incline Push Up',
    'Inchworm',
    'Jump Rope',
    'Jump Squat',
    'Jumping Jack',
    'Jumping Lunge',
    'Kettlebell Clean',
    'Kettlebell Goblet Squat',
    'Kettlebell Press',
    'Kettlebell Snatch',
    'Kettlebell Swing',
    'Lat Pulldown',
    'Lateral Raise',
    'Lateral Shuffle',
    'Leg Curl',
    'Leg Extension',
    'Leg Press',
    'Leg Raise',
    'Lunge',
    'Medicine Ball Slam',
    'Military Press',
    'Mountain Climber',
    'Nordic Curl',
    'Overhead Press',
    'Pec Deck',
    'Pike Push Up',
    'Pistol Squat',
    'Plank',
    'Plank Reach',
    'Plank Shoulder Tap',
    'Power Clean',
    'Preacher Curl',
    'Pull Up',
    'Push Press',
    'Push Up',
    'Rear Delt Fly',
    'Renegade Row',
    'Reverse Crunch',
    'Reverse Fly',
    'Reverse Lunge',
    'Romanian Deadlift',
    'Rowing',
    'Russian Twist',
    'Scissor Kick',
    'Seated Cable Row',
    'Seated Row',
    'Shoulder Press',
    'Side Lunge',
    'Side Plank',
    'Sit Up',
    'Skater Jump',
    'Skipping',
    'Sled Push',
    'Smith Machine Squat',
    'Snatch',
    'Speed Skater',
    'Spider Plank',
    'Split Squat',
    'Sprint',
    'Squat',
    'Squat Hold',
    'Squat Jump',
    'Stair Climb',
    'Standing Calf Raise',
    'Step Up',
    'Straight Leg Deadlift',
    'Sumo Deadlift',
    'Sumo Squat',
    'Superman Hold',
    'Thruster',
    'Toe Touch',
    'Torso Twist',
    'Tricep Dip',
    'Tricep Extension',
    'Turkish Get Up',
    'Tuck Jump',
    'Upright Row',
    'V Sit',
    'V Up',
    'Wall Ball',
    'Wall Sit',
    'Walking Lunge',
    'Wide Push Up',
    'Wood Chop',
    'Yoga Push Up',
];

export const systemExerciseDefinitions: SystemExerciseDefinitionSeed[] =
    systemExerciseDefinitionSeeds.map((name) => ({
        name,
        normalizedName: normalizeExerciseName(name),
        source: 'system',
        availability: 'both',
        createdAtMs: SYSTEM_EXERCISE_CREATED_AT_MS,
        updatedAtMs: SYSTEM_EXERCISE_CREATED_AT_MS,
    }));
